name: Docs Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate Docs
        run: |
          npm i --include=dev
          npm run build
          cp CNAME ./build/CNAME || cp ./static/CNAME ./build/CNAME || true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
